[package]
name = "sable-ast"
version = "0.1.0"
edition = "2024"

[dependencies]
getset = { workspace = true }
sable-common = { workspace = true }
ariadne = { workspace = true }
smallvec = { workspace = true }
typed-builder = { workspace = true }